theme: jekyll-theme-minimal
title: "ОРИОКС Мониторинг Бот"
lang: ru
description: "Бот для отслеживания изменений в образовательной электронной среде (ОРИОКС) НИУ МИЭТ orioks.miet.ru на платформе Telegram"

logo: img/logo.jpg
